// Generated by ReScript, PLEASE EDIT WITH CARE


function $$default(zora) {
  zora.test("Should run a test synchronously", (function (test) {
          test.equal(3.14, 3.14, "Should be a tasty dessert");
          
        }));
  
}

export {
  $$default ,
  $$default as default,
  
}
/* No side effect */
