version: "3.4"

x-shared-node-volume:
  volumes: &node_modules
    # Will overshadow the node_modules of the container host with the
    # preinstalled node_modules of the webui. This shall prevent host
    # dependend node_modules to be used inside the container.
    node_modules:/home/node/app/node_modules
  volumes: &readonly_node_modules
    node_modules:/home/node/app/node_modules:ro
  volumes: &mount-code
    ./:/home/node/app

x-app-service: &app-service
  build: .
  entrypoint: ["npm"]
  volumes:
    - *node_modules
    - *mount-code

services:
  dev:
    <<: *app-service
    command: ["run", "build:watch"]
    # Must set tty otherwise the service will stop immediatly after first
    # compilation.
    tty: true
    # Must run as root, as bsb will create directories which cannot be created
    # by the node user on the bind mount due to permissions.
    user: "root"

  serve:
    <<: *app-service
    command: ["run", "watch"]
    ports:
      - "3000:3000"

  test:
    <<: *app-service
    command: ["run", "test:watch"]
    tty: true
    volumes:
      - *mount-code
      - *readonly_node_modules

  # This service shall sync the persisted node_modules from the dev service
  # container over to the host. Otherwise the host node_module directory will
  # be empty. Leading to unresolved module errors and no autocompletion in
  # editors or IDEs. Syncing will happen everytime the package.json is changed.
  sync-node_modules-to-host:
    image: instrumentisto/rsync-ssh
    entrypoint: ["/bin/sh", "-c",
                'while true; do
                  printf "Syncing node_modules to host...\n";
                  rsync -az /container/node_modules/ /host/node_modules;
                  printf "Sync complete\n";
                  inotifyd -c /host/package.json;
                done' ]
    stop_grace_period: 2s
    depends_on:
      - dev
    volumes:
      - ./:/host/
      - node_modules:/container/node_modules:ro

  bug-tracker:
    image: glancingmind/git-bug
    ports:
      - "4000:4000"
    command: ["webui", "--host", "0.0.0.0", "--port", "4000", "--no-open"]
    volumes:
      - ./:/repository

volumes:
  node_modules:
